#!/usr/bin/env bash

super + Escape
	pkill -USR1 -x sxhkd
super + Return
	kitty
super + Tab
	/home/linuxbrew/.linuxbrew/bin/rofi -show drun
super + m 
	vlc ~/Music --random &
super + shift + m
	killall vlc
super + p
	polybar --config=~/.config/polybar/config.ini
super + shift + p
	killall polybar
super + w
	wal -i ~/Wallpaper &
