#!/usr/bin/env bash

super + Escape
	pkill -USR1 -x sxhkd
super + Return
	kitty
super + shift + Return
	/home/linuxbrew/.linuxbrew/bin/rofi -show drun
super + shift + m
	killall vlc
super + shift + p
	killall polybar
super + p
	polybar --config=~/.config/polybar/config.ini
super + Tab
	quick.sh
