#!/usr/bin/env fish
set var $(awk '{s+=$2} END {print s}' $argv)
set var2 $(awk '{if ($1 == "investing" ) print $2}' $argv)
set var3 $(awk '{if ($1 == "savings" ) print $2}' $argv)
echo "Total income = \$5400"
echo "Total investing contribution = \$$var2"
echo "Total saving contribution = \$$var3"
echo "Total expenses = \$$var"
