#!/usr/bin/env fish
set exp $(awk '{e+=$2} END {print e}' $argv)
set invs $(awk '/invest/ {print $2}' $argv)
set save $(awk '/sav/ {print $2}' $argv)
set income 5400
set expenses (math $income x 0.75)
set net_gain (math $income - $exp)
set invs_goal (math $income x 0.15)
set save_goal (math $income x 0.10)
echo "Total income = \$$income"
echo "Max expenses = \$$expenses"
echo "Recurring expenses = \$$exp"
echo "Net gain = \$$net_gain"
echo "Investing goal = \$$invs_goal"
echo "Total investing contribution = \$$invs"
echo "Savings goal \$$save_goal"
echo "Total saving contribution = \$$save"
