#!/usr/bin/zsh
sudo whoami
sudo apt update -y & 
echo "\n###update complete\n"
sudo apt upgrade -y & 
echo "\n###upgrade complete\n"
sudo apt autoremove -y &
echo "\n###autroremove complete\n"
sudo apt autoclean -y &
echo "\n###autoclean complete\n"
tldr --update &
echo "\n###tldr update complete"
